---
site_name: Kiwi
site_description: 'Kiwi portal to LLMs'
site_author: 'virtUOS'
docs_dir: docs/
repo_name: 'virtuos/kiwi'
repo_url: 'https://github.com/virtuos/kiwi'
nav:
    - Home: index.md
theme:
  name: 'material'
